# Form implementation generated from reading ui file 'sophos_exclusions.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(494, 328)
        MainWindow.setWindowOpacity(4.0)
        self.main_widget = QtWidgets.QWidget(parent=MainWindow)
        self.main_widget.setObjectName("main_widget")
        self.input_frame = QtWidgets.QFrame(parent=self.main_widget)
        self.input_frame.setGeometry(QtCore.QRect(0, 0, 461, 141))
        self.input_frame.setAutoFillBackground(True)
        self.input_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.input_frame.setObjectName("input_frame")
        self.id_label = QtWidgets.QLabel(parent=self.input_frame)
        self.id_label.setGeometry(QtCore.QRect(20, 10, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.id_label.setFont(font)
        self.id_label.setObjectName("id_label")
        self.secret_label = QtWidgets.QLabel(parent=self.input_frame)
        self.secret_label.setGeometry(QtCore.QRect(20, 80, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.secret_label.setFont(font)
        self.secret_label.setObjectName("id_label_2")
        self.id_input = QtWidgets.QLineEdit(parent=self.input_frame)
        self.id_input.setGeometry(QtCore.QRect(20, 30, 231, 21))
        self.id_input.setObjectName("id_input")
        self.secret_input = QtWidgets.QLineEdit(parent=self.input_frame)
        self.secret_input.setGeometry(QtCore.QRect(20, 100, 421, 21))
        self.secret_input.setObjectName("secret_input")
        self.button_frame = QtWidgets.QFrame(parent=self.main_widget)
        self.button_frame.setGeometry(QtCore.QRect(0, 150, 141, 121))
        self.button_frame.setAutoFillBackground(True)
        self.button_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.button_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.button_frame.setObjectName("button_frame")
        self.pushButton_dir = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_dir.setGeometry(QtCore.QRect(20, 10, 101, 24))
        self.pushButton_dir.setObjectName("pushButton")
        self.pushButton_run = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_run.setGeometry(QtCore.QRect(20, 40, 101, 24))
        self.pushButton_run.setObjectName("pushButton_2")
        self.pushButton_quit = QtWidgets.QPushButton(parent=self.button_frame)
        self.pushButton_quit.setGeometry(QtCore.QRect(20, 70, 101, 24))
        self.pushButton_quit.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.main_widget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 494, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Edits
        self.selected_folder = ""

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sophos Exclusion Export"))
        self.id_label.setText(_translate("MainWindow", "Token ID"))
        self.secret_label.setText(_translate("MainWindow", "Secret Key"))
        self.pushButton_dir.setText(_translate("MainWindow", "Change Folder"))
        self.pushButton_run.setText(_translate("MainWindow", "Run"))
        self.pushButton_quit.setText(_translate("MainWindow", "Quit"))
        self.pushButton_run.clicked.connect(self._on_change_dir)
        self.pushButton_quit.clicked.connect(self._on_quit)

    def _on_change_dir(self):
        folder = QtWidgets.QFileDialog.getExistingDirectory(
            parent=self,
            caption="Select Folder",
            dir=self.selected_folder or ""  # opens at last selected folder, or root
        )

    def _on_run(self):
        pass

    def _on_quit(self):
        sys.exit()



